remote_theme: eliottvincent/bay
header:
  pages:
    - name: Tess Monks
      slug: /     # <-- index.md
    - name: Personal Wesbite  # <-- blog.md

    
    
    
footer:
  show_powered_by: true
  contact:
    - name: Email
      value: tessmonks@g.harvard.edu
      link: mailto:tessmonks@g.harvard.edu
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/TessMonks
    - name: GitHub
      link: http://github.com/tessmonks
